name: searchy
description: A customizable Flutter search widget library providing search bars, fields, and scaffolds with flexible placement and search state management.
version: 0.2.0
homepage: https://github.com/Aikyuichi/searchy

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
